# Generated by Django 4.0.6 on 2022-07-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_instruction_options_remove_instruction_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['step']},
        ),
        migrations.AddField(
            model_name='instruction',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
